# Super basic pylint action

name: pylint

# Run on commits/PRs onto master
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Set up a python3 env and run pylint
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11.6"
      - run: pip install pylint==3.0.2 # -r requirements.txt
      - run: pylint --rcfile=.pylintrc $(git ls-files '*.py')
